 // adjust to your db client path
import { db } from ".";
import { tools } from "./schema";

export async function seedTools() {
  await db.insert(tools).values([
    {
      slug: "serp_search",
      name: "SERP Search",
      description: "Search the web and retrieve search engine results, links, titles, and snippets.",
      category: "search",
      type: "api",
      provider: "serpapi",
      icon: "search",
      status: "active",
      requireAuth: true,
      authType: "api_key",
      authProvider: "serpapi",
      capabilities: ["search_results", "link_extraction", "snippet_parsing"],
      useCases: ["research", "seo", "competitive_analysis"],
      permissions: ["read"],
      riskLevel: "low",
      canRead: true,
      canWrite: false,
      canDelete: false,
      canExecute: true,
      enabled: true,
    },
    {
      slug: "google_search",
      name: "Google Search",
      description: "Search the web via Google and retrieve ranked results, links, titles, and snippets.",
      category: "search",
      type: "api",
      provider: "google",
      icon: "search",
      status: "active",
      requireAuth: true,
      authType: "api_key",
      authProvider: "google",
      capabilities: ["search_results", "link_extraction", "snippet_parsing"],
      useCases: ["research", "fact_checking", "current_events"],
      permissions: ["read"],
      riskLevel: "low",
      canRead: true,
      canWrite: false,
      canDelete: false,
      canExecute: true,
      enabled: true,
    },
    {
      slug: "google_calendar",
      name: "Google Calendar",
      description: "Read upcoming events, check availability, and create or update calendar events.",
      category: "productivity",
      type: "mcp",
      provider: "google",
      icon: "calendar",
      status: "active",
      requireAuth: true,
      authType: "oauth2",
      authProvider: "google",
      capabilities: ["event_read", "event_create", "availability_check"],
      useCases: ["scheduling", "meeting_organization", "reminders"],
      permissions: ["read", "write"],
      approvalRules: { create_event: false, delete_event: true },
      riskLevel: "low",
      canRead: true,
      canWrite: true,
      canDelete: false,
      canExecute: true,
      enabled: true,
    },
    {
      slug: "browserbase",
      name: "Browserbase",
      description: "Navigate websites, interact with pages, and perform browser automation tasks.",
      category: "browser",
      type: "api",
      provider: "browserbase",
      icon: "browser",
      status: "active",
      requireAuth: true,
      authType: "api_key",
      authProvider: "browserbase",
      capabilities: ["browser_automation", "navigation", "form_filling", "scraping"],
      useCases: ["web_automation", "data_extraction", "site_interaction"],
      permissions: ["read", "write", "execute"],
      approvalRules: { navigate: false, form_submit: true, checkout: true },
      riskLevel: "medium",
      canRead: true,
      canWrite: true,
      canDelete: false,
      canExecute: true,
      enabled: true,
    },
    {
      slug: "slack",
      name: "Slack",
      description: "Read channels, search messages, and send notifications to Slack.",
      category: "communication",
      type: "mcp",
      provider: "slack",
      icon: "slack",
      status: "active",
      requireAuth: true,
      authType: "oauth2",
      authProvider: "slack",
      capabilities: ["send_message", "channel_post", "notifications"],
      useCases: ["team_communication", "alerts", "summaries"],
      permissions: ["read", "write"],
      approvalRules: { send_message: false, delete_message: true },
      riskLevel: "low",
      canRead: true,
      canWrite: true,
      canDelete: false,
      canExecute: true,
      enabled: true,
    },
    {
      slug: "gmail",
      name: "Gmail",
      description: "Search, read, draft and send emails or alerts through Gmail.",
      category: "communication",
      type: "mcp",
      provider: "google",
      icon: "mail",
      status: "active",
      requireAuth: true,
      authType: "oauth2",
      authProvider: "google",
      capabilities: ["email_read", "email_send", "email_search"],
      useCases: ["notifications", "email_communication", "alerts"],
      permissions: ["read", "write"],
      approvalRules: { send_email: true, delete_email: true },
      riskLevel: "medium",
      canRead: true,
      canWrite: true,
      canDelete: false,
      canExecute: true,
      enabled: true,
    },
    {
      slug: "notion",
      name: "Notion",
      description: "Search, read and update Notion pages, notes, and documents.",
      category: "productivity",
      type: "mcp",
      provider: "notion",
      icon: "notion",
      status: "active",
      requireAuth: true,
      authType: "oauth2",
      authProvider: "notion",
      capabilities: ["create_page", "update_page", "read_page"],
      useCases: ["document_management", "note_taking", "knowledge_base"],
      permissions: ["read", "write"],
      approvalRules: { create_page: false, delete_page: true },
      riskLevel: "low",
      canRead: true,
      canWrite: true,
      canDelete: false,
      canExecute: true,
      enabled: true,
    },
  ]);
}